### ISSUE TITLE
0.8.0 cannot open projects

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/QRAVEPlugin#79]
When I install QRave 0.8.0 from the store I am not able to open projects with the following error:

```
2022-10-05T15:19:31     WARNING    Traceback (most recent call last):
              File "/Users/matt/Library/Application Support/QGIS/QGIS3/profiles/user/python/plugins/qrave_toolbar/src/qrave_toolbar.py", line 354, in projectBrowserDlg
              self.toggle_widget(forceOn=True)
              File "/Users/matt/Library/Application Support/QGIS/QGIS3/profiles/user/python/plugins/qrave_toolbar/src/qrave_toolbar.py", line 262, in toggle_widget
              self.dockwidget = QRAVEDockWidget()
              File "/Users/matt/Library/Application Support/QGIS/QGIS3/profiles/user/python/plugins/qrave_toolbar/src/dock_widget.py", line 86, in __init__
              self.reload_tree()
              File "/Users/matt/Library/Application Support/QGIS/QGIS3/profiles/user/python/plugins/qrave_toolbar/src/dock_widget.py", line 138, in reload_tree
              basemap_states = get_checked_state(self.model.indexFromItem(self.basemaps.regions[region]), basemap_states)
              File "/Users/matt/Library/Application Support/QGIS/QGIS3/profiles/user/python/plugins/qrave_toolbar/src/dock_widget.py", line 123, in get_checked_state
              output.append((item.text(), expanded))
             AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by MattReimer** [comment]
Note. After restarting QGIS I was no longer able to reproduce this error. I'll close the ticket for now and we can re-open if it pops back up.
